# Generate-Replace.ps1

Write-Host ""
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "   AutoCAD Replace LISP Generator"
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""

# ============================================================
# INPUT REPLACEMENT
# ============================================================

$replaces = @()

while ($true) {

    $from = Read-Host "Replace from (kosong = selesai)"

    if ([string]::IsNullOrWhiteSpace($from)) {
        break
    }

    do {
        $to = Read-Host "Replace to"
    } while ($null -eq $to)

    $replaces += [PSCustomObject]@{
        From = $from
        To   = $to
    }

    Write-Host ""
}

if ($replaces.Count -eq 0) {
    Write-Host "Tidak ada data." -ForegroundColor Yellow
    exit
}

# ============================================================
# SHOW REPLACEMENT LIST
# ============================================================

Write-Host ""
Write-Host "Daftar Replace" -ForegroundColor Green
Write-Host "---------------------------"

$i = 1

foreach ($r in $replaces) {
    Write-Host ("[{0}] {1}  -->  {2}" -f $i, $r.From, $r.To)
    $i++
}

Write-Host ""

# ============================================================
# COMMAND NAME
# ============================================================

do {

    $cmdInput = Read-Host "Command name di AutoCAD (tanpa 'PS', tanpa spasi) [TEXT]"

    if ([string]::IsNullOrWhiteSpace($cmdInput)) {
        $cmdInput = "TEXT"
    }

    $cmdInput = $cmdInput -replace '\s',''

} while ([string]::IsNullOrWhiteSpace($cmdInput))

$cmdName = ("PS" + $cmdInput).ToUpper()

Write-Host ("Command  : {0}" -f $cmdName) -ForegroundColor Green
Write-Host ""

# ============================================================
# OUTPUT FILE
# ============================================================

$output = Read-Host ("Output file [{0}.lsp]" -f $cmdName)

if ([string]::IsNullOrWhiteSpace($output)) {
    $output = "$cmdName.lsp"
}

# ============================================================
# UNIQUE FUNCTION PREFIX
# ============================================================

# Supaya beberapa LSP hasil generator bisa di-load bersamaan
# tanpa function saling menimpa.

$fnPrefix = $cmdName

# ============================================================
# ESCAPE LISP STRING
# ============================================================

function Escape-LispString {
    param(
        [string]$Text
    )

    return $Text.Replace('\','\\').Replace('"','\"')
}

# ============================================================
# GENERATE REPLACE CODE
# ============================================================

$replaceCode = ""

foreach ($r in $replaces) {

    $from = Escape-LispString $r.From
    $to   = Escape-LispString $r.To

    $replaceCode += @"
        (setq newtxt ($($fnPrefix)-ReplaceString newtxt "$from" "$to"))
"@
}

# ============================================================
# GENERATE LISP
# ============================================================

$lsp = @"
;; ============================================================
;; AutoCAD Replace LISP
;; Command : $cmdName
;; Generated by Generate-Replace.ps1
;;
;; Behavior:
;; - Jika ada object yang dipilih:
;;     hanya object yang dipilih yang diproses
;;
;; - Jika tidak ada object yang dipilih:
;;     seluruh drawing diproses
;; ============================================================

(defun $($fnPrefix)-ReplaceString (str old new / pos)
    (while (setq pos (vl-string-search old str))
        (setq str
            (strcat
                (substr str 1 pos)
                new
                (substr str (+ pos (strlen old) 1))
            )
        )
    )
    str
)

(defun $($fnPrefix)-ProcessEntity (obj / txt newtxt)

    (if
        (and
            obj
            (vlax-property-available-p obj 'TextString)
        )
        (progn

            (setq txt (vla-get-TextString obj))
            (setq newtxt txt)

$replaceCode

            (if (/= txt newtxt)
                (progn

                    (vla-put-TextString obj newtxt)

                    (princ
                        (strcat
                            "\n"
                            txt
                            "  -->  "
                            newtxt
                        )
                    )

                    T
                )

                nil
            )
        )

        nil
    )
)

(defun $($fnPrefix)-ProcessObject (obj / att count)

    (setq count 0)

    (cond

        ;; ====================================================
        ;; TEXT / MTEXT / ATTDEF / ATTRIB
        ;; ====================================================

        ((member
            (vla-get-ObjectName obj)
            '(
                "AcDbText"
                "AcDbMText"
                "AcDbAttributeDefinition"
                "AcDbAttribute"
            )
        )

            (if ($($fnPrefix)-ProcessEntity obj)
                (setq count 1)
            )
        )

        ;; ====================================================
        ;; BLOCK REFERENCE
        ;; ====================================================

        ((and
            (= (vla-get-ObjectName obj) "AcDbBlockReference")
            (= :vlax-true (vla-get-HasAttributes obj))
        )

            (foreach att (vlax-invoke obj 'GetAttributes)

                (if ($($fnPrefix)-ProcessEntity att)
                    (setq count (1+ count))
                )

            )
        )
    )

    count
)

(defun $($fnPrefix)-ProcessSpace (space / obj count)

    (setq count 0)

    (vlax-for obj space

        (setq count
            (+ count
                ($($fnPrefix)-ProcessObject obj)
            )
        )
    )

    count
)

(defun $($fnPrefix)-ProcessSelection (ss / i obj count)

    (setq i 0)
    (setq count 0)

    (while (< i (sslength ss))

        (setq obj
            (vlax-ename->vla-object
                (ssname ss i)
            )
        )

        (setq count
            (+ count
                ($($fnPrefix)-ProcessObject obj)
            )
        )

        (setq i (1+ i))
    )

    count
)

(defun $($fnPrefix)-ProcessAll (doc / blocks blk lay count)

    (setq count 0)

    ;; ========================================================
    ;; Block Definitions
    ;; ========================================================

    (setq blocks (vla-get-Blocks doc))

    (vlax-for blk blocks

        (if
            (and
                (= :vlax-false (vla-get-IsLayout blk))
                (= :vlax-false (vla-get-IsXRef blk))
            )

            (setq count
                (+ count
                    ($($fnPrefix)-ProcessSpace blk)
                )
            )
        )
    )

    ;; ========================================================
    ;; Model Space
    ;; ========================================================

    (setq count
        (+ count
            ($($fnPrefix)-ProcessSpace
                (vla-get-ModelSpace doc)
            )
        )
    )

    ;; ========================================================
    ;; Paper Space / Layout
    ;; ========================================================

    (vlax-for lay (vla-get-Layouts doc)

        (setq count
            (+ count
                ($($fnPrefix)-ProcessSpace
                    (vla-get-Block lay)
                )
            )
        )
    )

    count
)

(defun c:$cmdName (/ doc ss count)

    (vl-load-com)

    (setq count 0)

    (setq doc
        (vla-get-ActiveDocument
            (vlax-get-acad-object)
        )
    )

    ;; ========================================================
    ;; CHECK PRE-SELECTED OBJECT
    ;; ========================================================

    ;; Jika user sudah memilih object sebelum menjalankan
    ;; command, gunakan selection tersebut.

    (setq ss (ssget "_I"))

    (if ss

        (progn

            (princ
                (strcat
                    "\nSelection ditemukan: "
                    (itoa (sslength ss))
                    " object."
                )
            )

            (princ
                "\nMemproses object yang dipilih..."
            )

            (setq count
                ($($fnPrefix)-ProcessSelection ss)
            )
        )

        ;; ====================================================
        ;; NO SELECTION
        ;; ====================================================

        (progn

            (princ
                "\nTidak ada selection."
            )

            (princ
                "\nMemproses seluruh drawing..."
            )

            (setq count
                ($($fnPrefix)-ProcessAll doc)
            )
        )
    )

    ;; ========================================================
    ;; REGEN
    ;; ========================================================

    (vla-Regen doc acAllViewports)

    ;; ========================================================
    ;; RESULT
    ;; ========================================================

    (princ
        (strcat
            "\n--------------------------------"
            "\nTotal perubahan : "
            (itoa count)
            "\nSelesai."
        )
    )

    (princ)
)
"@

# ============================================================
# WRITE FILE
# ============================================================

Set-Content -Path $output -Value $lsp -Encoding UTF8

Write-Host ""
Write-Host "Generated : $output" -ForegroundColor Green
Write-Host "Command   : $cmdName" -ForegroundColor Green
Write-Host ""
